Feature/add malfunction
io2-2021-wed-brodka/C_Backend pull request #153
Opened 2021-05-30 19:45 UTC by potomskit

2021-05-30 20:07 UTC, aolesiakmini reviewed
MalfunctionsController.AddMalfunction wysypie się jeśli Object.Bike lub Object.ReportingUser byłby nullem.

Startup niepotrzebna spacja.

MalfunctionsRepositoryTests.Add kilka niepotrzebnych pustych linii.

MalfunctionService.GetMalfunction w linii 49 tekst powinien być "Malfunction not found" zamiast "Bike not found"

Tak ogólnie: wydaje mi się że MalfunctionsService jest niepotrzebny. Lepiej byłoby mieć część zadań związanych z malfunctionsami w UsersService (Get oraz Post), a część w TechsService (delete). Wtedy nie ma problemu z UserContext.

Poza tym wszystko gites

2021-06-01 16:56 UTC, marcinggalinski commented
> Tak ogólnie: wydaje mi się że MalfunctionsService jest niepotrzebny. Lepiej byłoby mieć część zadań związanych z malfunctionsami w UsersService (Get oraz Post), a część w TechsService (delete). Wtedy nie ma problemu z UserContext.

Ja powtórzę, co napisałem w CR do PR #150. Moim zdaniem lepiej właśnie mieć `MalfunctionsService` niż rozbijać rzeczy związanie z usterkami po innych miejscach (w szczególności nie widzę wtedy po co jest `TechsService`)

2021-06-01 17:12 UTC, marcinggalinski commented
@aolesiakmini możesz dawać komentarze do konkretnych linii, wtedy jest dużo prościej ;)

> MalfunctionsController.AddMalfunction wysypie się jeśli Object.Bike lub Object.ReportingUser byłby nullem.
`response.Object` jest używane tylko gdy `response.Status` jest równy `Status.Success` - w takiej sytuacji możemy oczekiwać, że `Object` nie jest nullem (a gdyby był to nawet dobrze, że poleci wyjątek, bo to jakaś abnormalna sytuacja)

> Startup niepotrzebna spacja.
> 
> MalfunctionsRepositoryTests.Add kilka niepotrzebnych pustych linii.
Stylistycznych rzeczy jest jeszcze kilka, ale ten fragment tym bardziej pokazuje, żeby dawać komentarze do kodu, a nie zbiorczy komentarz do PRa

2021-06-01 17:26 UTC, marcinggalinski requested changes

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.DataAccess/Repositories/Abstract/IMalfunctionsRepository.cs
> +using BikesRentalServer.Models;
ja z moim upośledzeniem klasycznie ładnie poproszę o posortowanie usingów, ale możesz mnie olać (i tak to zrobię w końcu ;p)

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.DataAccess/Repositories/MalfunctionsRepository.cs
> +        }
Brakujące newline (raczej stawiajmy puste linie pomiędzy metodami)

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Services/Abstract/IMalfunctionsService.cs
> +        #region Basics
Po tym też można dać pustą linię, ale to też detal

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Services/Abstract/IMalfunctionsService.cs
> +        ServiceActionResult<Malfunction> GetMalfunction(string bike);
bike -> bikeId. W tym momencie nazwa sugeruje przekazanie roweru (czyli czego, nazwy? bike.ToString()?)

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Services/MalfunctionsService.cs
> +        private readonly IUsersRepository _usersRepository;
pola też oddzielajmy pustą linią od metod (w tym przypadku konstruktora)

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Services/MalfunctionsService.cs
> +        public MalfunctionsService(UserContext userContext, IMalfunctionsRepository malfunctionRepository, IBikesRepository bikesRepository, IUsersRepository usersRepository)
Można się pokusić o rozbicie tego na 4 linie, bo długie się robi (nie wiem jak to w IDE wygląda, może nie ma potrzeby)

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Services/MalfunctionsService.cs
> +            _userContext = userContext;
Znowu moje upośledzenie się odzywa: userContext przekazujemy jako pierwszy parametr, to można go jako pierwszego przypisać... Ale to w ogóle bez znaczenia ze strony działania

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Services/MalfunctionsService.cs
> +            if(bike.User == null || (bike.User.Username != _userContext.Username))
spacja po ifie, proponuję użyć `is null`, nawiasy nie są tu potrzebne (niemożliwym jest zrobienie logical or ze stringiem `bike.User.Username`)

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Services/MalfunctionsService.cs
> +                return ServiceActionResult.EntityNotFound<Malfunction>("Bike not found");
tak jak Adam pisał - powinno być "Malfunction not found"

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Tests/ServicesTests/MalfunctionsServiceTests/MalfunctionsServiceTestsBase.cs
> +        protected IMalfunctionsService getMalfunctionsService(string username = "maklovitz", UserRole role = UserRole.User)
W C# korzystamy z `PascalCase`, nie z `camelCase`

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Tests/ServicesTests/MalfunctionsServiceTests/MalfunctionsServiceTestsBase.cs
> +        protected IMalfunctionsService getMalfunctionsService(string username = "maklovitz", UserRole role = UserRole.User)
also oddziel tę metodę newlinem od tych propert powyżej

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.WebApi/Controllers/MalfunctionsController.cs
> +        }
daj tu newline

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.WebApi/Controllers/MalfunctionsController.cs
> +            return response.Status switch
możesz dodać na koniec takiego case'a `_`, który wyłapie nieprawidłowe wartości i rzuci wyjątkiem (patrz inne kontrolery)

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.WebApi/Controllers/MalfunctionsController.cs
> +        public ActionResult <GetMalfunctionResponse> AddMalfunction(AddMalfunctionRequest request)
niepotrzebna spacja po `ActionResult`

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.WebApi/Controllers/MalfunctionsController.cs
> +            return null;
Jeśli to nie jest zaimplementowane to lepiej rzucić `NotImplementedException`

2021-06-01 17:26 UTC, marcinggalinski commented on Backend/BikesRentalServer.Tests/RepositoriesTests/MalfunctionsRepositoryTests/Add.cs
> +
a tu niepotrzebny newline

2021-06-01 17:26 UTC, marcinggalinski reviewed
@aolesiakmini 
> Wtedy nie ma problemu z UserContext.

A jaki jest problem z UserContext tutaj?

2021-06-01 21:26 UTC, marcinggalinski approved these changes

2021-06-01 21:26 UTC, piotrduperas approved these changes

2021-06-01 21:27 UTC, merged